name: CI
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:

  build:
    runs-on: ubuntu-latest   
    steps:
    #----------------------------------------------
    #       check-out repo
    #----------------------------------------------
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    #----------------------------------------------
    #       check commit message
    #----------------------------------------------
      - name : Check commit messages
        uses: wagoid/commitlint-github-action@v4 